### ISSUE TITLE
Install on OSX

### ISSUE THREAD

**Issue by stevesloka** [xlab/go-lambda#2]
When I try to install on OSX, I get the following. There is a note about non-linux systems needing to setup the container. Is the thought to use the container on non-linux to do all the work?

```
❯❯❯ go get github.com/xlab/go-lambda
# github.com/cheggaaa/pb
../github.com/cheggaaa/pb/pb_x.go:21: undefined: syscall.TCGETS
../github.com/cheggaaa/pb/pb_x.go:22: undefined: syscall.TCSETS
```

**Comment by xlab** [comment]
@stevesloka 
I have mac osx too (and it always has been working fine with pb). This package was responsible for a progressbar when you choose to download the source.zip 🙈
Which OS X version do you have? I'll quickly solve this or just remove the feature.

**Comment by xlab** [comment]
Pffft, https://github.com/cheggaaa/pb/issues/54

`cheggaaa/pb` was stable for all the time I know it since Go 1.4, disabling it in 8305050 for now until their master will be stable again.

@stevesloka it's good to know which version of Go did you use.

**Comment by stevesloka** [comment]
Hey @xlab I'm on OSX 10.11.2 running Go version "go1.5 darwin/amd64"
